name: sdui_engine
description: "A production-grade Server-Driven UI (SDUI) framework for Flutter. Build hyper-dynamic, completely remote home screens using clean JSON payloads and declarative architectures."
version: 0.5.0
homepage: "https://github.com/luck-shay/flutterHomeScreenPackage"
repository: "https://github.com/luck-shay/flutterHomeScreenPackage"
issue_tracker: "https://github.com/luck-shay/flutterHomeScreenPackage/issues"

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
